# Generated by Django 5.0.6 on 2024-07-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_django_backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
